### ISSUE TITLE
Strange likelihood

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedprobr#2] opened 2018-08-25 16:15 UTC
``` r
library(pedtools)
library(pedprobr)
H1 = nuclearPed(1)
for (i in 1:5)
  H1 = addParents(H1, founders(H1)[2], verbose = FALSE)
m1 = marker(H1, "1" = 1, "3" = 1:2)
H1 = setMarkers(H1,m1)
likelihood(H1,1)
#> [1] 3.375
```

Created on 2018-08-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thoree** [comment] 2018-08-26 05:58
Here's a simpler version where I manage to get a wrong likelihood.
If I create the pedigree in a more natural way, eg by using linearPed, the problem goes away.
``` r
library(pedtools)
library(pedprobr)
x1 = nuclearPed(1)
for (i in 1:2)
  x1 = addParents(x1, founders(x1)[2], verbose = FALSE)
m1 = marker(x1, "3" = 1:2)
likelihood(x1, m1) 
#> [1] 1.5
```

Created on 2018-08-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by magnusdv** [comment] 2018-08-26 18:07
Confirmed. As shown in the following output from `pedlikCompare`, the bug is unique to `pedprobr`, implying that it was introduced during or after code transfer from `paramlink`:

``` r
library(pedtools)
library(pedlikCompare)

x1 = nuclearPed(1)
for (i in 1:2)
  x1 = addParents(x1, founders(x1)[2], verbose = FALSE)

m1 = marker(x1, "3" = 1:2)

compare(x1, m1)
#> Program `pedprobr`...finished in 0.05 seconds
#> Program `paramlink`...finished in 0.00 seconds
#> Program `Familias`...finished in 0.00 seconds
#> Program `ElstonStewart`...finished in 0.03 seconds
#> Program `merlin`...finished in 0.34 seconds
#> 
#> ===> ANSWERS ARE NOT THE SAME <===
#> # A tibble: 5 x 4
#>   program       likelihood  lnlik   time
#>   <chr>              <dbl>  <dbl>  <dbl>
#> 1 pedprobr           1.5    0.405 0.0468
#> 2 paramlink          0.5   -0.693 0     
#> 3 Familias           0.5   -0.693 0     
#> 4 ElstonStewart      0.5   -0.693 0.0312
#> 5 merlin             0.500 -0.693 0.336
```

**Comment by magnusdv** [comment] 2018-08-26 19:05
This is related to the internal pedigree order. I see now that `addParents()` appends parents at the *end* of the pedigree, instead of *before* the individual they are parenting. (This is unfortunate for several reasons; needs to be fixed in `pedtools`.) 

After reordering so that parents precede their children, the likelihood is correct:

``` r
library(pedtools)
library(pedprobr)

x1 = nuclearPed(1)
x1 = addParents(x1, 2, verbose = F)
x1 = addParents(x1, 4, verbose = F)
x1 = setMarkers(x1, marker(x1, "3" = 1:2))

likelihood(x1, 1) 
#> [1] 1.5

y = parents_before_children(x1)
likelihood(y, 1)
#> [1] 0.5
```

I need to dig a little more to solve this.

**Comment by magnusdv** [comment] 2018-08-30 08:52
The particular examples above now give correct likelihoods. However, this is only because `addParents()` behaves better (see above) - I haven't had time to fix the actual bug.

I'm closing this now and opening a new issue with an updated reprex.

**Closed as completed by magnusdv** 2018-08-30 08:52 UTC
Labels: bug
